#!/bin/sh

# Устанавливаем LAN IP 10.10.11.1/24
uci set network.lan.ipaddr='10.10.11.1'
uci set network.lan.netmask='255.255.255.0'
uci commit network

# Русский язык в LuCI по умолчанию
uci set luci.main.lang='ru'
uci commit luci

# Отключаем телеметрию и прочий мусор (опционально)
uci set gluon-nodeinfo.@owner[0].contact=''
uci set system.@system[0].hostname='OpenWrt-Mesh'
uci commit system

# IPv6 сервисы OFF (на всякий случай)
if [ -x /etc/init.d/odhcpd ]; then
    /etc/init.d/odhcpd stop
    /etc/init.d/odhcpd disable
fi

# Перезагружаем сеть (необязательно, sysupgrade сам применит)
/etc/init.d/network restart

exit 0
